### ISSUE TITLE
Unique Reaction

### ISSUE THREAD

**Issue by shenshen1122** [jiuntian/IssueTrackerAssignment#12]
If my group and I decided to limit at most 1 reaction per user on 1 single comment. 
However, for any given comment, the .json file does not record who made those reactions. Furthermore, some of the comments have up to 11 reactions while having only 4 users. 

Can I remove ALL the reactions on a comment in the .json file to suit the implementation using a database?

**Comment by jiuntian** [comment]
Can. 

Make sure that you're able to export all the data to json. (Data structure can be different as you need to change it for additional features)

**Comment by shenshen1122** [comment]
Just to double confirm, 

1) I will be removing all the reactions from .json file

2) If a user chooses to export all the data to .json file, the exported json file will contain the reaction count for each comment, However, the unique reaction made by 1 user on 1 comment will only be stored in MySQL as a reaction table with composite Primary Key ( userID, commentID)

**Comment by jiuntian** [comment]
The json file is actually to be serve as **backup** purpose, in which case one can dump all data into json file, and can restore all data from json file.
