### ISSUE TITLE
Top performer in team

### ISSUE THREAD

**Issue by limzhengqian** [jiuntian/IssueTrackerAssignment#14]
For the report generation, how do we determine the top performer?

**Comment by jiuntian** [comment]
You can decide on your own, what aspect should be the top performer, i.e: The one resolved most ticket in this week is top performer. Or it can also be, the one take lowest time to resolve ticket in average is top performer. It is just like different boss have different KPI for their employee, and now you are the boss to decide this.

**Comment by limzhengqian** [comment]
For the statistic part, aren't they the same stuff? (indicate how many issues per timeframe)
- Time (the number of issues in day/week/month)
- Plot a line graph that show the issue frequency over selected time range

**Comment by jiuntian** [comment]
Ya
