### ISSUE TITLE
ADTs

### ISSUE THREAD

**Issue by chimtingshing** [jiuntian/IssueTrackerAssignment#16]
I know this may be a simple question but I'm just asking for confirmation.

Based on the questions, the comment class and issue class should be an ADT. In my case, my comment and issue classes are just classes with private variables, constructor and getter/setter. Is this considered an ADT?

**Comment by jiuntian** [comment]
It's okay.

**Comment by PuaZhiXian** [comment]
In the ADT right can i have other method except the getter/setter method ?

**Comment by jiuntian** [comment]
It's ok.
