### ISSUE TITLE
Extra feature-Access Control List

### ISSUE THREAD

**Issue by PUAJINGYI** [jiuntian/IssueTrackerAssignment#18]
If we implement which type of user is allowed to perform particular actions, is it the access control list?
For example:
Only creator and assignee can change the status.
We define the only assignee can set the status of the issue to "Resolved", "Reopened",while the creator only can set the status to "Closed" and "Reopened".

**Comment by jiuntian** [comment]
You should include also who can
- see
- edit
- create
- delete

**Comment by PUAJINGYI** [comment]
So is it mean I need to store this information together with the issue detail(id, title, description...)?
and when I display issue detail for user, the user will not see the info like who can see, edit, create, delete but this kind of info will appear in another table of list which only admin can show it. Is it what you mean?

**Comment by jiuntian** [comment]
Ya you can do this way.

**Comment by PUAJINGYI** [comment]
ok,thank you demo
