### ISSUE TITLE
Reopen and closed

### ISSUE THREAD

**Issue by ACE07-Sev** [jiuntian/IssueTrackerAssignment#21]
Hey there, sorry is it possible to just have closed and remove reopen feature since it's not realistic ?
It gets really messy if closed or resolved issues remain in a frozen status until someone reopens them again, in reality ppl just create a new ticket. Can we please implement it our own way?
we wish to remove the issues that get closed.
With regards
A.C.E

**Comment by jiuntian** [comment]
In the reality, the closed issue shall not be deleted, as it will always be
used as a reference in future.

In fact, one can find a lot of solution in solving the problems on tools
from closed GitHub issues. Thankfully they did not delete it. This is one
of the examples in reality.

In project management, the closed ticket, will be reference again in
future, in case some one want to check the work, or even the one who work
on the ticket forgot what he did.

Still, you may add a delete function to delete it manually though.

Hope this helps.
