### ISSUE TITLE
Status of an Issue

### ISSUE THREAD

**Issue by shenshen1122** [jiuntian/IssueTrackerAssignment#6]
Could you kindly elaborate on when should the status of an issue be categorized into one of 
"Open", "In Progress", "Resolved", "Closed".

**Comment by jiuntian** [comment]
Let's take this example:
When a ticket is opened, it will be "Open".
When someone is taking the responsibility for this particular ticket, and starting his progress, it will be "in progress".
When the ticket is done or completed, it will be "Resolved".
If the ticket is cancelled, it is moved to "Closed".
You may refer to the issue cycle figure given in the question.
![image](https://user-images.githubusercontent.com/13869695/118407234-70553b80-b6b2-11eb-8359-00bf6f42975c.png)

**Comment by shenshen1122** [comment]
May I know if the below description is correct?

creator -> "open"      (open a new issue/ reopen a issue), 
            -> "closed"    (close a issue after assignee resolved it)

assignee -> "in progress" (starts working on a issue assigned)
               -> "resolved"     (once he/she has provided solution to the issue)

**Comment by jiuntian** [comment]
It is not restrict to just creator to close the ticket, assignee can also close it whenever necessarily. Same goes to reopen, assignee can reopen the ticket, when he/she think that the problem still persist or did not solved.

Feel free to try some of common issue tracker system online to know more about these: Jira (free trial available)

**Comment by jiuntian** [comment]
What's more, you can take this Github Issue as an example as well. Both you and me can close this ticket, and reopen it.

**Comment by shenshen1122** [comment]
Can the creator set the status of an issue to "In Progress" & "Resolved"?

**Comment by jiuntian** [comment]
ideally, creator should be able to move the issue to "Resolved" as well. "In progress" would be better to be reported by the one who is working on the issue.

However, there are many different philosophy of issue lifecycle,  I am just giving some suggestions only.

**Comment by shenshen1122** [comment]
Noted with thanks
