### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by shenshen1122** [jiuntian/IssueTrackerAssignment#8]
what does it mean by changelog?
What exactly should we display to the user?
Could you further elaborate on this by giving examples?

**Comment by jiuntian** [comment]
This is example of changelog in Facebook Post, you can try your own as well if you have Facebook account
![image](https://user-images.githubusercontent.com/13869695/118804300-1c776c00-b8d7-11eb-85ed-c550050c3eda.png)
You have to show:
1. Who change the post/comment?
2. When is the changes?
3. What is changed?

If you like to, you can also add:
1. Why change? (the changer have to enter his reason)

**Comment by shenshen1122** [comment]
Since changelog of an issue should be recorded & viewed when requested.

1) What are the attributes of an issue that are allowed to change?
2) Who are eligible to make those changes to an issue? creator? assignee? or anyone?

**Comment by jiuntian** [comment]
You decide it. Can made your own assumption.

**Comment by shenshen1122** [comment]
Noted with thanks
